# Variables defined for hybris-boot

TARGET_HYBRIS_BOOT_OUT := $(PRODUCT_OUT)/hybris-boot
TARGET_HYBRIS_BOOT_OUT_BIN := $(TARGET_HYBRIS_BOOT_OUT)/bin
TARGET_HYBRIS_BOOT_OUT_SBIN := $(TARGET_HYBRIS_BOOT_OUT)/sbin

TARGET_HYBRIS_BOOT_OUT_UNSTRIPPED := $(TARGET_OUT_UNSTRIPPED)
TARGET_HYBRIS_BOOT_OUT_SBIN_UNSTRIPPED := $(TARGET_OUT_UNSTRIPPED)/sbin
TARGET_HYBRIS_BOOT_OUT_BIN_UNSTRIPPED := $(TARGET_OUT_UNSTRIPPED)/bin
